"use client";

import { useEffect, useState } from "react";
import { marketDataService, type AssetSearchResult } from "../services/marketData";
import { formatMoney } from "../utils/portfolio";

export function AssetSearch({ selected, onSelect, allowManual=true }:{selected:AssetSearchResult|null;onSelect(asset:AssetSearchResult|null):void;allowManual?:boolean}) {
  const [query,setQuery]=useState(selected?.ticker ?? ""); const [results,setResults]=useState<AssetSearchResult[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [warnings,setWarnings]=useState<string[]>([]);
  useEffect(()=>{ if(selected || query.trim().length<2){setResults([]);return;} const timer=setTimeout(async()=>{setLoading(true);setError("");try{const response=await marketDataService.searchAssets(query);setResults(response.data);setWarnings(response.warnings??[]);}catch(e){setError(e instanceof Error?e.message:"Search unavailable");}finally{setLoading(false);}},350);return()=>clearTimeout(timer);},[query,selected]);
  const manual=():AssetSearchResult=>({ticker:query.trim().toUpperCase(),name:query.trim().toUpperCase(),assetClass:"Stock",marketRegion:"US",market:"Manual",currency:"USD",provider:"manual",providerId:query.trim().toUpperCase(),quote:null});
  if(selected) return <div className="selected-asset"><div><strong>{selected.ticker}</strong><span>{selected.name}</span><small>{selected.market} · {selected.assetClass} · {selected.currency}</small></div><div>{selected.quote?<><strong>{formatMoney(selected.quote.price,selected.quote.currency,2)}</strong><small>{selected.quote.isDelayed?"Delayed":"Live"} · {selected.quote.source}</small></>:<><strong>Price unavailable</strong><small>Manual price remains available</small></>}</div><button type="button" onClick={()=>{onSelect(null);setQuery("");}}>Change</button></div>;
  return <div className="asset-search"><label>Asset<input autoFocus role="combobox" aria-expanded={results.length>0} aria-controls="asset-results" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ticker or company name…" autoComplete="off" /></label>{loading&&<p className="search-state">Searching official market sources…</p>}{error&&<p className="form-error">{error}</p>}{!loading&&query.length>=2&&<div id="asset-results" role="listbox" className="search-results">{results.map(item=><button type="button" role="option" key={`${item.provider}:${item.providerId}`} onClick={()=>onSelect(item)}><div><strong>{item.ticker}</strong><span>{item.name}</span><small>{item.market} · {item.assetClass} · {item.currency}</small></div><div>{item.quote?formatMoney(item.quote.price,item.quote.currency,2):"Price unavailable"}</div></button>)}{!results.length&&!error&&<p>No matching assets yet.</p>}</div>}{warnings.length>0&&<p className="search-warning">{warnings.join(" · ")}</p>}{allowManual&&query.trim()&&<button type="button" className="manual-asset-link" onClick={()=>onSelect(manual())}>Can&apos;t find it? Add as a manual asset →</button>}</div>;
}
