"use client";

import { useState } from "react";
import type { WatchlistItem } from "../types/portfolio";
import type { AssetSearchResult } from "../services/marketData";
import { formatMoney, formatPct } from "../utils/portfolio";
import { AssetSearch } from "./AssetSearch";
type Draft=Omit<WatchlistItem,"id">;
const fromItem=(p:WatchlistItem):AssetSearchResult=>({...p,quote:p.currentPrice>0?{ticker:p.ticker,price:p.currentPrice,currency:p.currency,change:null,changePercent:p.quoteChangePercent,timestamp:p.lastPriceAt??new Date().toISOString(),source:p.provider,isDelayed:true}:null});
export function WatchlistForm({initial,existing,onCancel,onSave,onEditExisting}:{initial?:WatchlistItem;existing:WatchlistItem[];onCancel():void;onSave(value:Draft|WatchlistItem):void;onEditExisting(item:WatchlistItem):void}){const[asset,setAsset]=useState<AssetSearchResult|null>(initial?fromItem(initial):null);const[target,setTarget]=useState(initial?.targetEntry??0);const[manualPrice,setManualPrice]=useState(initial?.currentPrice??0);const[error,setError]=useState("");const duplicate=asset&&!initial?existing.find(i=>i.ticker===asset.ticker&&i.marketRegion===asset.marketRegion):undefined;const price=asset?.quote?.price??manualPrice;const distance=price>0&&target>0?(price-target)/target*100:null;const submit=(e:React.FormEvent)=>{e.preventDefault();if(!asset)return setError("Select an asset first.");if(duplicate)return setError(`${asset.ticker} already exists.`);if(!Number.isFinite(target)||target<=0)return setError("Target entry must be above zero.");const value={...asset,currentPrice:price,targetEntry:target,priceSource:asset.provider==="manual"?"manual" as const:"auto" as const,lastPriceAt:asset.quote?.timestamp??null,quoteChangePercent:asset.quote?.changePercent??null,quoteError:asset.quote?null:"Price unavailable"};delete (value as Partial<AssetSearchResult>).quote;onSave(initial?{...value,id:initial.id}:value as Draft);};return <form className="entity-form smart-form" onSubmit={submit}><AssetSearch selected={asset} onSelect={v=>{setAsset(v);if(v)setManualPrice(v.quote?.price??0);}}/>{duplicate&&<div className="duplicate-warning"><strong>{asset?.ticker} is already on your watchlist.</strong><button type="button" onClick={()=>onEditExisting(duplicate)}>Update item</button></div>}<div className="form-grid primary-fields"><label>Target entry price<input type="number" min="0.00000001" step="any" value={target||""} onChange={e=>setTarget(Number(e.target.value))}/></label>{asset?.provider==="manual"&&<label>Manual current price<input type="number" min="0" step="any" value={manualPrice||""} onChange={e=>setManualPrice(Number(e.target.value))}/></label>}</div>{asset&&target>0&&<div className="target-preview"><span>Current <strong>{price>0?formatMoney(price,asset.currency,2):"Unavailable"}</strong></span><span>Target <strong>{formatMoney(target,asset.currency,2)}</strong></span><span>Distance <strong className={distance!==null&&distance<=0?"profit":""}>{formatPct(distance)}</strong></span><em className={distance!==null&&distance<=0?"entry":""}>{distance===null?"NO PRICE":distance<=0?"ENTRY ZONE":"WATCHING"}</em></div>}{error&&<p className="form-error">{error}</p>}<footer><button type="button" className="button secondary" onClick={onCancel}>Cancel</button><button className="button primary" disabled={!asset||!!duplicate}>Save item</button></footer></form>}
