import test from "node:test";
import assert from "node:assert/strict";
import type { PortfolioData, Position } from "../app/types/portfolio.ts";
import { findDuplicatePosition, getAllocation, getMetrics, getPerformanceLeaders, INITIAL_DATA, mergeQuoteRefresh, positionMetrics, shouldRecordSnapshot, toTwd, watchlistDistance } from "../app/utils/portfolio.ts";

export const position = (overrides: Partial<Position> = {}): Position => ({ id:"p1",ticker:"TEST",name:"Test",assetClass:"Stock",marketRegion:"US",market:"US",currency:"USD",provider:"manual",providerId:"TEST",quantity:2.5,averageCost:100,currentPrice:120,priceSource:"manual",lastPriceAt:null,quoteChange:null,quoteChangePercent:null,quoteError:null,createdAt:"2026-01-01T00:00:00.000Z",...overrides });
export const data = (positions: Position[], settings: Partial<PortfolioData["settings"]> = {}): PortfolioData => ({ ...INITIAL_DATA, positions, settings:{...INITIAL_DATA.settings,usdTwdRate:32,...settings} });

test("position calculation supports fractional shares and FX",()=>{const result=positionMetrics(position(),32);assert.equal(result.cost,8000);assert.equal(result.marketValue,9600);assert.equal(result.profitLoss,1600);assert.equal(result.returnPct,20)});
test("portfolio totals include converted cash",()=>{const result=getMetrics(data([position()],{baseCurrency:"USD",twdCash:3200,usdCash:10}));assert.equal(result.invested,250);assert.equal(result.holdings,300);assert.equal(result.cash,110);assert.equal(result.total,410)});
test("position weight denominator includes cash",()=>{const result=getMetrics(data([position({currency:"TWD",quantity:1,currentPrice:19350,averageCost:18000})],{baseCurrency:"TWD",twdCash:24450,usdCash:0}));assert.equal(result.total,43800);assert.ok(Math.abs(result.rows[0].marketValue/result.totalTwd*100-44.178)<.01)});
test("zero cost basis returns null and never Infinity or NaN",()=>{const result=positionMetrics(position({averageCost:0}),32);assert.equal(result.returnPct,null);assert.ok(Number.isFinite(result.profitLoss))});
test("missing FX never uses a hard-coded rate or creates Infinity",()=>{assert.equal(toTwd(100,"USD",0),0);const result=getMetrics(data([position()],{baseCurrency:"USD",usdTwdRate:0}));assert.equal(result.total,0);assert.ok(Number.isFinite(result.total))});
test("market exposure and asset allocation use independent taxonomies",()=>{const value=data([position({id:"tw",ticker:"0050",currency:"TWD",assetClass:"ETF",marketRegion:"Taiwan",quantity:1,currentPrice:100,averageCost:90}),position({id:"us",ticker:"VT",currency:"TWD",assetClass:"ETF",marketRegion:"US",quantity:1,currentPrice:200,averageCost:190})],{twdCash:0});assert.deepEqual(getAllocation(value,"assetClass").map(x=>x.label),["ETF"]);assert.deepEqual(getAllocation(value,"marketRegion").map(x=>x.label),["Taiwan","US"])});
test("winner and loser are selected only from positive and negative returns",()=>{const onlyWinner=getPerformanceLeaders(data([position({ticker:"0050",currency:"TWD",averageCost:100,currentPrice:107.5})]));assert.equal(onlyWinner.winner?.position.ticker,"0050");assert.equal(onlyWinner.loser,null);const onlyLoser=getPerformanceLeaders(data([position({ticker:"VT",currency:"TWD",averageCost:100,currentPrice:90})]));assert.equal(onlyLoser.winner,null);assert.equal(onlyLoser.loser?.position.ticker,"VT")});
test("watchlist distance and unavailable quote behavior are stable",()=>{assert.equal(watchlistDistance(90,100),-10);assert.equal(watchlistDistance(110,100),10);assert.equal(watchlistDistance(0,100),null);assert.equal(watchlistDistance(Number.NaN,100),null)});
test("duplicate positions match ticker and market region, excluding current edit",()=>{const existing=position({id:"a",ticker:"0050",marketRegion:"Taiwan"});assert.equal(findDuplicatePosition([existing],{ticker:"0050",marketRegion:"Taiwan"})?.id,"a");assert.equal(findDuplicatePosition([existing],{ticker:"0050",marketRegion:"US"}),undefined);assert.equal(findDuplicatePosition([existing],{ticker:"0050",marketRegion:"Taiwan"},"a"),undefined)});
test("snapshot policy deduplicates same value within a reasonable window",()=>{const last={dateTime:"2026-08-15T00:00:00.000Z",portfolioValue:10000,investedAmount:9000};assert.equal(shouldRecordSnapshot(last,10000,new Date("2026-08-15T01:00:00.000Z").getTime()),false);assert.equal(shouldRecordSnapshot(last,11000,new Date("2026-08-15T00:10:00.000Z").getTime()),false);assert.equal(shouldRecordSnapshot(last,11000,new Date("2026-08-15T01:00:00.000Z").getTime()),true)});
test("failed quote refresh preserves the last successful price",()=>{const current=position({provider:"coingecko",providerId:"bitcoin",priceSource:"auto",currentPrice:118000,lastPriceAt:"2026-08-15T00:00:00.000Z"});const refreshed=mergeQuoteRefresh([current],{});assert.equal(refreshed[0].currentPrice,118000);assert.equal(refreshed[0].lastPriceAt,current.lastPriceAt);assert.equal(refreshed[0].quoteError,"Price unavailable")});
