import test from "node:test";
import assert from "node:assert/strict";
import type { AssetRef } from "../app/types/portfolio.ts";
import { MarketDataService } from "../app/services/marketData/index.ts";
import { handleMarketData } from "../api/market-data.ts";

const json=(value:unknown)=>new Response(JSON.stringify(value),{status:200,headers:{"content-type":"application/json"}});
test("market search maps Taiwan, US and crypto assets to their real providers",{concurrency:false},async()=>{
 const originalFetch=globalThis.fetch, originalKey=process.env.FINNHUB_API_KEY;
 globalThis.fetch=async(input)=>{const url=new URL(String(input));if(url.hostname==="openapi.twse.com.tw")return json([{Date:"1150814",Code:"0050",Name:"元大台灣50",ClosingPrice:"193.50",MonthlyAveragePrice:"190"},{Date:"1150814",Code:"2330",Name:"台積電",ClosingPrice:"1200",MonthlyAveragePrice:"1180"}]);if(url.pathname.endsWith("/search")&&url.hostname.includes("coingecko")){const q=url.searchParams.get("query")??"";const coins={BTC:{id:"bitcoin",name:"Bitcoin",symbol:"btc",market_cap_rank:1},ETH:{id:"ethereum",name:"Ethereum",symbol:"eth",market_cap_rank:2},SOL:{id:"solana",name:"Solana",symbol:"sol",market_cap_rank:6}} as const;return json({coins:q in coins?[coins[q as keyof typeof coins]]:[]})}if(url.pathname.includes("simple/price")){const ids=url.searchParams.get("ids")??"";return json(Object.fromEntries(ids.split(",").map(id=>[id,{usd:118000,usd_24h_change:2,last_updated_at:1786700000}])))}if(url.hostname==="finnhub.io"&&url.pathname.endsWith("/search")){const q=url.searchParams.get("q");return json({result:q==="NVDA"?[{symbol:"NVDA",displaySymbol:"NVDA",description:"NVIDIA CORP",type:"Common Stock"}]:[{symbol:"VT",displaySymbol:"VT",description:"Vanguard Total World Stock ETF",type:"ETF"}]})}if(url.hostname==="finnhub.io"&&url.pathname.endsWith("/quote"))return json({c:200,d:2,dp:1,t:1786700000});throw new Error(`Unexpected provider URL ${url}`)};
 try{
  delete process.env.FINNHUB_API_KEY;
  const noKey=await (await handleMarketData(new Request("http://localhost/api/market-data?action=search&q=NVDA"))).json() as {warnings:string[]};assert.ok(noKey.warnings.includes("Unavailable · FINNHUB_API_KEY not configured"));
  const tw=await (await handleMarketData(new Request("http://localhost/api/market-data?action=search&q=0050"))).json() as {data:Array<{provider:string;ticker:string;name:string;market:string;assetClass:string;currency:string;quote:{isDelayed:boolean}}>};assert.deepEqual({provider:tw.data[0].provider,ticker:tw.data[0].ticker,name:tw.data[0].name,market:tw.data[0].market,assetClass:tw.data[0].assetClass,currency:tw.data[0].currency,delayed:tw.data[0].quote.isDelayed},{provider:"twse",ticker:"0050",name:"元大台灣50",market:"TWSE",assetClass:"ETF",currency:"TWD",delayed:true});
  const twStock=await (await handleMarketData(new Request("http://localhost/api/market-data?action=search&q=2330"))).json() as {data:Array<{provider:string;ticker:string}>};assert.deepEqual([twStock.data[0].ticker,twStock.data[0].provider],["2330","twse"]);
  for(const [ticker,id] of [["BTC","bitcoin"],["ETH","ethereum"],["SOL","solana"]]){const coin=await (await handleMarketData(new Request(`http://localhost/api/market-data?action=search&q=${ticker}`))).json() as {data:Array<{provider:string;providerId:string;ticker:string}>};assert.deepEqual([coin.data[0].ticker,coin.data[0].provider,coin.data[0].providerId],[ticker,"coingecko",id])}
  process.env.FINNHUB_API_KEY="server-test-key";
  for(const ticker of ["NVDA","VT"]){const us=await (await handleMarketData(new Request(`http://localhost/api/market-data?action=search&q=${ticker}`))).json() as {data:Array<{provider:string;ticker:string;assetClass:string}>};assert.equal(us.data[0].provider,"finnhub");assert.equal(us.data[0].ticker,ticker);assert.equal(us.data[0].assetClass,ticker==="VT"?"ETF":"Stock")}
 }finally{globalThis.fetch=originalFetch;if(originalKey===undefined)delete process.env.FINNHUB_API_KEY;else process.env.FINNHUB_API_KEY=originalKey}
});

test("refresh-all deduplicates assets and reuses the short-lived quote cache",{concurrency:false},async()=>{const originalFetch=globalThis.fetch;let submitted=0,requests=0;globalThis.fetch=async(_input,init)=>{requests++;const body=JSON.parse(String(init?.body)) as {assets:AssetRef[]};submitted=body.assets.length;return json({data:{"coingecko:bitcoin":{ticker:"BTC",price:118000,currency:"USD",change:null,changePercent:2,timestamp:"2026-08-15T00:00:00.000Z",source:"CoinGecko",isDelayed:false}},warnings:[]})};try{const service=new MarketDataService();const asset:AssetRef={ticker:"BTC",name:"Bitcoin",assetClass:"Crypto",marketRegion:"Crypto",market:"Crypto",currency:"USD",provider:"coingecko",providerId:"bitcoin"};await service.getQuotes([asset,asset],true);await service.getQuotes([asset],false);assert.equal(submitted,1);assert.equal(requests,1)}finally{globalThis.fetch=originalFetch}});

test("frontend converts HTML and malformed JSON responses into a clean service error",{concurrency:false},async()=>{const originalFetch=globalThis.fetch;try{for(const response of [new Response("<!doctype html><html></html>",{status:200,headers:{"content-type":"text/html"}}),new Response("not-json",{status:200,headers:{"content-type":"application/json"}})]){globalThis.fetch=async()=>response.clone();const service=new MarketDataService();await assert.rejects(()=>service.searchAssets("0050"),{message:"Market data service unavailable."})}}finally{globalThis.fetch=originalFetch}});
