import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import handler from "../api/market-data.ts";

interface Result { status:number; headers:Record<string,string>; body:string; }
async function invoke(method:string,url:string,body?:unknown):Promise<Result>{const result:Result={status:200,headers:{},body:""};await handler({method,url,headers:{host:"ascent.test"},body},{status(code){result.status=code;return this},setHeader(name,value){result.headers[name.toLowerCase()]=value},send(value){result.body=value}});return result}
const providerJson=(value:unknown)=>new Response(JSON.stringify(value),{status:200,headers:{"content-type":"application/json"}});

test("Vercel uses a native market-data function and excludes every /api/* path from SPA fallback",()=>{assert.equal(existsSync("api/market-data.ts"),true);assert.equal(existsSync("api/_market-data.ts"),false);const config=JSON.parse(readFileSync("vercel.json","utf8")) as {rewrites:Array<{source:string;destination:string}>};assert.equal(config.rewrites.length,1);assert.equal(config.rewrites[0].destination,"/index.html");const rewrite=new RegExp(`^${config.rewrites[0].source}$`);assert.equal(rewrite.test("/portfolio/holdings"),true);assert.equal(rewrite.test("/api/market-data"),false);assert.equal(rewrite.test("/api/anything"),false)});

test("native Vercel API returns JSON for search, quotes and FX",{concurrency:false},async()=>{const originalFetch=globalThis.fetch,originalKey=process.env.FINNHUB_API_KEY;delete process.env.FINNHUB_API_KEY;globalThis.fetch=async(input)=>{const url=new URL(String(input));if(url.hostname==="openapi.twse.com.tw")return providerJson([{Date:"1150814",Code:"0050",Name:"元大台灣50",ClosingPrice:"106.40",MonthlyAveragePrice:"103.97"},{Date:"1150814",Code:"2330",Name:"台積電",ClosingPrice:"1200",MonthlyAveragePrice:"1180"}]);if(url.hostname.includes("coingecko"))return providerJson({coins:[]});if(url.hostname==="api.frankfurter.dev")return providerJson({date:"2026-08-14",rates:{TWD:31.4}});throw new Error(`Unexpected URL ${url}`)};try{
 for(const ticker of ["0050","2330"]){const result=await invoke("GET",`/api/market-data?action=search&q=${ticker}`);assert.equal(result.status,200);assert.match(result.headers["content-type"],/^application\/json/);const payload=JSON.parse(result.body) as {data:Array<{ticker:string;name:string;market:string;assetClass:string;currency:string;provider:string}>};assert.equal(payload.data[0].ticker,ticker);assert.equal(payload.data[0].provider,"twse");assert.equal(payload.data[0].market,"TWSE");assert.equal(payload.data[0].currency,"TWD");if(ticker==="0050"){assert.equal(payload.data[0].name,"元大台灣50");assert.equal(payload.data[0].assetClass,"ETF")}}
 const noKey=await invoke("GET","/api/market-data?action=search&q=NVDA");assert.equal(noKey.status,200);assert.match(noKey.headers["content-type"],/^application\/json/);assert.match(noKey.body,/FINNHUB_API_KEY not configured/);
 const quotes=await invoke("POST","/api/market-data",{action:"quotes",assets:[]});assert.equal(quotes.status,200);assert.deepEqual(JSON.parse(quotes.body),{data:{},warnings:[]});
 const fx=await invoke("GET","/api/market-data?action=fx&pair=USD/TWD");assert.equal(fx.status,200);assert.match(fx.headers["content-type"],/^application\/json/);assert.equal((JSON.parse(fx.body) as {data:{ticker:string}}).data.ticker,"USD/TWD");
 const unknown=await invoke("GET","/api/market-data?action=unknown");assert.equal(unknown.status,503);assert.match(unknown.headers["content-type"],/^application\/json/);assert.doesNotMatch(unknown.body,/<!doctype/i);assert.equal((JSON.parse(unknown.body) as {error:string}).error,"Unknown action");
 }finally{globalThis.fetch=originalFetch;if(originalKey===undefined)delete process.env.FINNHUB_API_KEY;else process.env.FINNHUB_API_KEY=originalKey}});
