"use client";
import type { PortfolioData } from "../types/portfolio";
import { formatMoney, formatPct, getAllocation, getMetrics, getPerformanceLeaders } from "../utils/portfolio";
const palette=["#4c8dff","#7d91b5","#9e86cc","#6dad8b","#d0a15a"];
export function OverviewPage({data,onAdd,onDemo,onViewPortfolio}:{data:PortfolioData;onAdd():void;onDemo():void;onViewPortfolio():void}){
 const metrics=getMetrics(data), assetAllocation=getAllocation(data,"assetClass"), marketAllocation=getAllocation(data,"marketRegion"), leaders=getPerformanceLeaders(data), divisor=data.settings.baseCurrency==="USD"?data.settings.usdTwdRate:1;
 const sorted=metrics.rows.map(row=>({...row,value:divisor>0?row.marketValue/divisor:0})).sort((a,b)=>b.value-a.value);
 const gradient=assetAllocation.length?`conic-gradient(${assetAllocation.map((item,index)=>`${palette[index%palette.length]} ${assetAllocation.slice(0,index).reduce((s,x)=>s+x.pct,0)}% ${assetAllocation.slice(0,index+1).reduce((s,x)=>s+x.pct,0)}%`).join(",")})`:"#171b22";
 if(!data.positions.length&&metrics.cash===0)return <><Summary metrics={metrics} currency={data.settings.baseCurrency}/><section className="empty-state"><span className="empty-symbol">↗</span><p className="eyebrow">START YOUR ASCENT</p><h2>Your portfolio is empty.</h2><p>Add your first position to start tracking investments, allocation and performance with real data.</p><div><button className="button primary" onClick={onAdd}>＋ Add position</button><button className="button secondary" onClick={onDemo}>Load demo data</button></div><small>Demo data is never loaded automatically.</small></section></>;
 const points=data.portfolioHistory.slice(-30), max=Math.max(...points.map(x=>x.portfolioValue),1);
 return <><Summary metrics={metrics} currency={data.settings.baseCurrency}/><div className="overview-grid"><section className="section-block performance"><div className="section-heading"><div><p className="eyebrow">PERFORMANCE</p><h2>Portfolio history</h2></div><span>{data.portfolioHistory.length} real snapshots</span></div>{points.length<2?<div className="no-history"><strong>History is being recorded.</strong><span>Ascent saves a snapshot after a meaningful change, without duplicating identical values.</span></div>:<div className="history-bars" aria-label="Portfolio value history">{points.map(point=><div key={point.dateTime} style={{height:`${Math.max(8,point.portfolioValue/max*100)}%`}} title={`${new Date(point.dateTime).toLocaleString()}: NT$${point.portfolioValue.toFixed(0)}`}/>)}</div>}</section><section className="section-block allocation"><div className="section-heading"><div><p className="eyebrow">ALLOCATION</p><h2>By asset class</h2></div></div><div className="allocation-body"><div className="donut" style={{background:gradient}}><span>{formatMoney(metrics.total,data.settings.baseCurrency)}</span></div><AllocationList items={assetAllocation} currency={data.settings.baseCurrency}/></div></section></div>
 <section className="section-block market-exposure"><div className="section-heading"><div><p className="eyebrow">MARKET EXPOSURE</p><h2>Where your assets trade</h2></div></div><AllocationList items={marketAllocation} currency={data.settings.baseCurrency}/></section>
 <section className="section-block analytics"><div className="section-heading"><div><p className="eyebrow">PORTFOLIO ANALYTICS</p><h2>Performance and exposure</h2></div></div><div className="analytics-grid"><Metric label="Largest winner" value={leaders.winner?.position.ticker??"—"} detail={leaders.winner?formatPct(leaders.winner.returnPct):"No winning positions"} tone="profit"/><Metric label="Largest loser" value={leaders.loser?.position.ticker??"—"} detail={leaders.loser?formatPct(leaders.loser.returnPct):"No losing positions"} tone="loss"/>{(["Taiwan","US","Crypto"] as const).map(region=>{const item=marketAllocation.find(entry=>entry.label===region);return <Metric key={region} label={`${region} exposure`} value={`${(item?.pct??0).toFixed(1)}%`} detail="of total portfolio"/>})}</div></section>
 <section className="section-block top-holdings"><div className="section-heading"><div><p className="eyebrow">CONCENTRATION</p><h2>Top holdings</h2></div><button className="text-button" onClick={onViewPortfolio}>View portfolio →</button></div><div className="top-holdings-list">{sorted.slice(0,5).map(row=><div key={row.position.id}><span><strong>{row.position.ticker}</strong><small>{row.position.name}</small></span><em>{metrics.total?(row.value/metrics.total*100).toFixed(1):"0.0"}%</em><strong>{formatMoney(row.value,data.settings.baseCurrency)}</strong></div>)}</div></section></>;
}
function AllocationList({items,currency}:{items:ReturnType<typeof getAllocation>;currency:"TWD"|"USD"}){return <div className="allocation-list">{items.map((item,index)=><div key={item.label}><i style={{background:palette[index%palette.length]}}/><span>{item.label}</span><strong>{formatMoney(item.amount,currency)}</strong><em>{item.pct.toFixed(1)}%</em></div>)}</div>}
function Summary({metrics,currency}:{metrics:ReturnType<typeof getMetrics>;currency:"TWD"|"USD"}){return <section className="summary-strip"><div className="summary-main"><span>Total portfolio value</span><strong>{formatMoney(metrics.total,currency)}</strong><small>Base currency · {currency}</small></div><div><span>Today&apos;s P/L</span><strong className={metrics.todayPl>=0?"profit":"loss"}>{metrics.todayPlAvailable?formatMoney(metrics.todayPl,currency):"—"}</strong><small>{metrics.todayPlAvailable?"Available previous closes":"Previous close unavailable"}</small></div><div><span>Total P/L</span><strong className={metrics.profitLoss>=0?"profit":"loss"}>{formatMoney(metrics.profitLoss,currency)}</strong><small>Unrealized</small></div><div><span>Total return</span><strong className={metrics.returnPct===null?"":metrics.returnPct>=0?"profit":"loss"}>{formatPct(metrics.returnPct)}</strong><small>Against cost basis</small></div><div><span>Available cash</span><strong>{formatMoney(metrics.cash,currency)}</strong><small>TWD + USD cash</small></div></section>}
function Metric({label,value,detail,tone=""}:{label:string;value:string;detail:string;tone?:string}){return <div className="analytics-metric"><span>{label}</span><strong className={value==="—"?"":tone}>{value}</strong><small className={value==="—"?"":tone}>{detail}</small></div>}
