"use client";
import { useMemo,useState } from "react";
import type { Position } from "../types/portfolio";
import { usePortfolio } from "../hooks/use-portfolio";
import { formatMoney,formatPct,formatQuantity,getMetrics } from "../utils/portfolio";
import { useConfirmation } from "../components/ConfirmationDialog";
type Sort="ticker"|"value"|"pl"|"return"|"weight";
export function PortfolioPage({onAdd,onEdit}:{onAdd():void;onEdit(position:Position):void}){const{data,deletePosition,refreshPrices}=usePortfolio();const confirmAction=useConfirmation();const[sort,setSort]=useState<Sort>("value");const metrics=getMetrics(data),divisor=data.settings.baseCurrency==="USD"?data.settings.usdTwdRate:1;const rows=useMemo(()=>[...metrics.rows].sort((a,b)=>sort==="ticker"?a.position.ticker.localeCompare(b.position.ticker):sort==="pl"?b.profitLoss-a.profitLoss:sort==="return"?(b.returnPct??-Infinity)-(a.returnPct??-Infinity):b.marketValue-a.marketValue),[metrics.rows,sort]);
 const remove=async(p:Position)=>{if(await confirmAction({title:`Delete ${p.ticker}?`,message:"This removes the position from your portfolio. Transactions remain unchanged.",confirmLabel:"Delete position"}))deletePosition(p.id)};
 return <section className="section-block holdings-block"><div className="section-heading"><div><p className="eyebrow">POSITIONS</p><h2>Holdings</h2><span>{data.positions.length} tracked assets</span></div><button className="button primary" onClick={onAdd}>＋ Add position</button></div>{!data.positions.length?<div className="inline-empty"><strong>No holdings yet.</strong><span>Add a position to begin tracking cost, value, P/L and weight.</span><button className="button secondary" onClick={onAdd}>Add first position</button></div>:<><div className="sort-bar" aria-label="Sort positions"><span>Sort by</span>{([['ticker','Ticker'],['value','Market value'],['pl','P/L'],['return','Return'],['weight','Weight']] as [Sort,string][]).map(([key,label])=><button key={key} className={sort===key?"active":""} onClick={()=>setSort(key)}>{label}</button>)}</div><div className="table-scroll"><table><thead><tr><th>Asset</th><th>Quantity</th><th>Avg cost</th><th>Current price</th><th>Market value</th><th>P/L</th><th>Return</th><th>Weight</th><th className="actions">Actions</th></tr></thead><tbody>{rows.map(row=>{const value=divisor>0?row.marketValue/divisor:0,weight=metrics.total?value/metrics.total*100:0;return <tr key={row.position.id}><td><strong>{row.position.ticker}</strong><span>{row.position.name}<i>{row.position.assetClass} · {row.position.marketRegion}</i></span></td><td>{formatQuantity(row.position.quantity,row.position.assetClass==="Crypto")}</td><td>{formatMoney(row.position.averageCost,row.position.currency,2)}</td><td><strong>{row.position.currentPrice>0?formatMoney(row.position.currentPrice,row.position.currency,2):"Unavailable"}</strong><span className={row.position.quoteChangePercent!=null?(row.position.quoteChangePercent>=0?"profit":"loss"):""}>{row.position.quoteChangePercent!=null?formatPct(row.position.quoteChangePercent):(row.position.quoteError||`${row.position.priceSource} price`)}</span></td><td>{formatMoney(value,data.settings.baseCurrency)}</td><td className={row.profitLoss>=0?"profit":"loss"}>{formatMoney(divisor>0?row.profitLoss/divisor:0,data.settings.baseCurrency)}</td><td className={row.returnPct===null?"":row.returnPct>=0?"profit":"loss"}>{formatPct(row.returnPct)}</td><td>{weight.toFixed(1)}%</td><td className="actions"><button onClick={()=>onEdit(row.position)}>Edit</button>{row.position.quoteError&&row.position.priceSource==="auto"&&<button onClick={()=>void refreshPrices(true)}>Retry</button>}<button className="danger-link" onClick={()=>void remove(row.position)}>Delete</button></td></tr>})}</tbody></table></div></>}</section>}
