"use client";
import { useEffect,useRef,useState } from "react";
import type { Currency,PortfolioSettings,PriceSource } from "../types/portfolio";
import { usePortfolio } from "../hooks/use-portfolio";
import { formatTime,INITIAL_DATA,migratePortfolioData } from "../utils/portfolio";
import { useConfirmation } from "../components/ConfirmationDialog";
export function SettingsPage(){const{data,updateSettings,importData,reset,refreshPrices,refreshing}=usePortfolio();const confirmAction=useConfirmation();const[settings,setSettings]=useState<PortfolioSettings>(data.settings);const[notice,setNotice]=useState("");const fileRef=useRef<HTMLInputElement>(null);const set=(key:keyof PortfolioSettings,value:string|number)=>setSettings(current=>({...current,[key]:value}));
 useEffect(()=>setSettings(data.settings),[data.settings]);
 const save=(e:React.FormEvent)=>{e.preventDefault();if(!Number.isFinite(settings.usdTwdRate)||settings.usdTwdRate<=0||settings.twdCash<0||settings.usdCash<0)return setNotice("FX rate must be above zero and cash cannot be negative.");updateSettings(settings);setNotice("Settings saved.")};
 const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`ascent-portfolio-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);setNotice("Portfolio backup exported.")};
 const importFile=async(file?:File)=>{if(!file)return;try{const migrated=migratePortfolioData(JSON.parse(await file.text()));if(!migrated)throw new Error();if(!await confirmAction({title:"Replace current portfolio?",message:"Ascent will automatically keep a pre-import backup in this browser, then load this JSON file.",confirmLabel:"Import backup",tone:"primary"}))return;importData(migrated);setSettings(migrated.settings);setNotice("Backup imported and migrated to V3.")}catch{setNotice("This file is not a valid Ascent portfolio backup.")}finally{if(fileRef.current)fileRef.current.value=""}};
 const resetData=async()=>{if(await confirmAction({title:"Reset all local data?",message:"This removes positions, watchlist, transactions, settings and history from this browser.",confirmLabel:"Reset all data"})){reset();setSettings(INITIAL_DATA.settings);setNotice("All local portfolio data was reset.")}};
 const retryFx=async()=>{await refreshPrices(true);};
 return <div className="settings-layout"><form className="section-block settings-section" onSubmit={save}><div className="section-heading"><div><p className="eyebrow">PORTFOLIO PREFERENCES</p><h2>Settings</h2><span>Valuation and cash balances</span></div></div><div className="settings-fields">
 <label>Base currency<select value={settings.baseCurrency} onChange={e=>set("baseCurrency",e.target.value as Currency)}><option>TWD</option><option>USD</option></select><small>Portfolio totals are displayed in this currency.</small></label>
 <label>FX source<select value={settings.fxSource} onChange={e=>set("fxSource",e.target.value as PriceSource)}><option value="auto">Automatic · Frankfurter</option><option value="manual">Manual</option></select><small>{settings.fxSource==="auto"?`Last update: ${formatTime(data.settings.fxLastUpdated)}`:"You control the conversion rate."}</small></label>
 <label>USD / TWD rate<input type="number" min="0.0001" step="any" disabled={settings.fxSource==="auto"} value={settings.usdTwdRate} onChange={e=>set("usdTwdRate",Number(e.target.value))}/><small>{data.settings.fxError||"Used for all USD conversions."}</small></label>
 <label>TWD cash<input type="number" min="0" step="any" value={settings.twdCash} onChange={e=>set("twdCash",Number(e.target.value))}/><small>Available cash held in Taiwan dollars.</small></label><label>USD cash<input type="number" min="0" step="any" value={settings.usdCash} onChange={e=>set("usdCash",Number(e.target.value))}/><small>Converted at your USD/TWD rate.</small></label>
 </div><footer>{settings.fxSource==="auto"&&<button type="button" className="button secondary" disabled={refreshing} onClick={()=>void retryFx()}>{refreshing?"Refreshing…":"Retry FX"}</button>}<button className="button primary">Save settings</button></footer></form>
 <section className="section-block data-section"><div className="section-heading"><div><p className="eyebrow">LOCAL DATA</p><h2>Backup & recovery</h2><span>Your data stays in this browser unless you export it.</span></div></div><div className="data-actions"><div><strong>Export portfolio JSON</strong><span>Download positions, watchlist, transactions, settings and real snapshots.</span><button className="button secondary" onClick={exportData}>↓ Export data</button></div><div><strong>Import portfolio JSON</strong><span>V1 backups are migrated; manual prices are preserved.</span><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={e=>void importFile(e.target.files?.[0])}/><button className="button secondary" onClick={()=>fileRef.current?.click()}>↑ Import data</button></div><div className="danger-zone"><strong>Reset all data</strong><span>Clear this device and return Ascent to its initial empty state.</span><button className="button danger" onClick={()=>void resetData()}>Reset all data</button></div></div></section>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}</div>}
